name: Test Smart Contract

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Clarinet
        run: |
          wget -nv https://github.com/hirosystems/clarinet/releases/download/v2.4.0/clarinet-linux-x64-glibc.tar.gz -O clarinet.tar.gz
          tar -xf clarinet.tar.gz
          chmod +x clarinet
          sudo mv clarinet /usr/local/bin/

      - name: Run Tests
        run: clarinet test
